import type { ShopItemDto } from '~/models/dto/shopItemDto';
import { Color } from '~/models/enums/color';
import { Size } from '~/models/enums/size';
import type { CategoryDto } from '~/models/dto/categoryDto';
import type { Review } from '~/models/review';

interface FakeDatabase {
  shopItems: ShopItemDto[];
  categories: CategoryDto[];
  reviews: Review[];
}

export const fakeDatabase: FakeDatabase = {
  shopItems: [
    {
      id: '1',
      name: 'Classic T-Shirt',
      brand: 'Adidas',
      description: 'A comfortable and stylish classic t-shirt.',
      categories: [{ name: 'Clothing' }],
      colors: [Color.Red, Color.Blue, Color.Green],
      sizes: [Size.XXL, Size.XL, Size.L],
      price: 299,
      discountedPrice: 249,
      stock: 50,
      image: '/images/categories/clothing.png',
      slug: 'classic-t-shirt',
    },
    {
      id: '2',
      name: 'Sporty Sneakers',
      brand: 'Nike',
      description:
        'High-performance sporty sneakers for your active lifestyle.',
      categories: [{ name: 'Footwear' }, { name: 'Sneakers' }],
      colors: [Color.Yellow, Color.Purple, Color.Orange],
      sizes: [Size.M, Size.S],
      price: 3999,
      stock: 30,
      image: '/images/categories/clothing.png',
      slug: 'sporty-sneakers',
    },
    {
      id: '3',
      name: 'Elegant Watch',
      brand: 'Cartier',
      description: 'An elegant and stylish watch for any occasion.',
      categories: [{ name: 'Accessories' }, { name: 'Watches' }],
      colors: [Color.Black, Color.White, Color.Yellow],
      sizes: [Size.None],
      price: 9999,
      stock: 20,
      image: '/images/categories/clothing.png',
      slug: 'elegant-watch',
    },
    {
      id: '4',
      name: 'Casual Jeans',
      brand: 'Levi Strauss & Co',
      description: 'Comfortable and stylish jeans for a casual look.',
      categories: [{ name: 'Clothing' }, { name: 'Jeans' }],
      colors: [Color.Blue, Color.Black, Color.Gray],
      sizes: [Size.XL, Size.L, Size.M],
      price: 4959,
      stock: 25,
      image: '/images/categories/clothing.png',
      slug: 'casual-jeans',
    },
    {
      id: '5',
      name: 'Running Shoes',
      brand: 'Adidas',
      description: 'Lightweight and durable shoes for your running sessions.',
      categories: [{ name: 'Footwear' }, { name: 'Sneakers' }],
      colors: [Color.Blue, Color.Green, Color.Gray],
      sizes: [Size.M, Size.L, Size.XL],
      price: 5959,
      discountedPrice: 5459,
      stock: 40,
      image: '/images/categories/clothing.png',
      slug: 'running-shoes',
    },
    {
      id: '6',
      name: 'Leather Handbag',
      brand: 'Chanel',
      description: 'A classic leather handbag to complement your style.',
      categories: [{ name: 'Accessories' }, { name: 'Handbags' }],
      colors: [Color.Blue, Color.Black, Color.White],
      sizes: [Size.None],
      price: 7999,
      stock: 15,
      image: '/images/categories/clothing.png',
      slug: 'leather-handbag',
    },
    {
      id: '7',
      name: 'Classic T-Shirt',
      brand: 'Uniqlo',
      description: 'A comfortable and stylish classic t-shirt.',
      categories: [{ name: 'Clothing' }],
      colors: [Color.Red, Color.Blue, Color.Green],
      sizes: [Size.XXL, Size.XL, Size.L, Size.M, Size.S],
      price: 399,
      stock: 30,
      image: '/images/categories/clothing.png',
      slug: 'classic-t-shirt-2',
    },
    {
      id: '8',
      name: 'Sporty Sneakers',
      brand: 'Puma',
      description:
        'High-performance sporty sneakers for your active lifestyle.',
      categories: [{ name: 'Footwear' }, { name: 'Sneakers' }],
      colors: [Color.Yellow, Color.Purple, Color.Orange],
      sizes: [Size.L, Size.M, Size.S, Size.XS],
      price: 4919,
      discountedPrice: 2919,
      stock: 10,
      image: '/images/categories/clothing.png',
      slug: 'sporty-sneakers-2',
    },
    {
      id: '9',
      name: 'Elegant Watch',
      brand: 'Rolex',
      description: 'An elegant and stylish watch for any occasion.',
      categories: [{ name: 'Accessories' }, { name: 'Watches' }],
      colors: [Color.Black, Color.White, Color.Yellow],
      sizes: [Size.None],
      price: 19999,
      stock: 0,
      image: '/images/categories/clothing.png',
      slug: 'elegant-watch-2',
    },
    {
      id: '10',
      name: 'Casual Jeans',
      brand: 'Armani',
      description: 'Comfortable and stylish jeans for a casual look.',
      categories: [{ name: 'Clothing' }, { name: 'Jeans' }],
      colors: [Color.Blue, Color.Black, Color.Gray],
      sizes: [Size.XL, Size.L, Size.M, Size.S],
      price: 6959,
      discountedPrice: 5959,
      stock: 5,
      image: '/images/categories/clothing.png',
      slug: 'casual-jeans-2',
    },
    {
      id: '11',
      name: 'Running Shoes',
      brand: 'Nike',
      description: 'Lightweight and durable shoes for your running sessions.',
      categories: [{ name: 'Footwear' }, { name: 'Sneakers' }],
      colors: [Color.Blue, Color.Green, Color.Gray],
      sizes: [Size.M, Size.L, Size.XL],
      price: 7999,
      stock: 0,
      image: '/images/categories/clothing.png',
      slug: 'running-shoes-2',
    },
    {
      id: '12',
      name: 'Leather Handbag',
      brand: 'Louis Vuitton',
      description: 'A classic leather handbag to complement your style.',
      categories: [{ name: 'Accessories' }, { name: 'Handbags' }],
      colors: [Color.Blue, Color.Black, Color.White],
      sizes: [Size.None],
      price: 9999,
      discountedPrice: 8999,
      stock: 15,
      image: '/images/categories/clothing.png',
      slug: 'leather-handbag-2',
    },
  ],
  categories: [
    {
      id: '1',
      name: 'Clothing',
      slug: 'clothing',
      image: '/images/categories/clothing.png',
    },
    {
      id: '2',
      name: 'Footwear',
      slug: 'footwear',
      image: '/images/categories/footwear.png',
    },
    {
      id: '3',
      name: 'Sneakers',
      slug: 'sneakers',
      image: '/images/categories/sneakers.png',
    },
    {
      id: '4',
      name: 'Accessories',
      slug: 'accessories',
      image: '/images/categories/accessories.png',
    },
    {
      id: '5',
      name: 'Watches',
      slug: 'watches',
      image: '/images/categories/watches.png',
    },
    {
      id: '6',
      name: 'Jeans',
      slug: 'jeans',
      image: '/images/categories/jeans.png',
    },
    {
      id: '7',
      name: 'Handbags',
      slug: 'handbags',
      image: '/images/categories/handbags.png',
    },
  ],
  reviews: [
    {
      id: '1',
      rating: 5,
      text: "Absolutely love the variety and quality of clothes at this shop! Found the perfect dress for my friend's wedding. Will definitely be coming back for more.",
      name: 'Emily Johnson',
      position: 'Fashion Enthusiast',
      image: '/images/avatars/avatar1.png',
    },
    {
      id: '2',
      rating: 5,
      text: 'Great experience shopping here! The staff was helpful, and I found some trendy pieces that fit perfectly into my wardrobe.',
      name: 'Alex Chen',
      position: 'Style Blogger',
      image: '/images/avatars/avatar2.png',
    },
    {
      id: '3',
      rating: 4.8,
      text: 'Amazing store! I found a stunning outfit for a special occasion. The staff provided excellent assistance, making my shopping experience memorable.',
      name: 'Michael Thompson',
      position: 'Fashion Influencer',
      image: '/images/avatars/avatar2.png',
    },
    {
      id: '4',
      rating: 5,
      text: 'This shop never disappoints! I always find unique pieces that make me stand out. The quality is top-notch, and the prices are fair. Highly recommend!',
      name: 'Emma Roberts',
      position: 'Fashion Enthusiast',
      image: '/images/avatars/avatar1.png',
    },
    {
      id: '5',
      rating: 4.5,
      text: 'Good selection of clothes, but the checkout process was a bit slow. Staff were friendly, though, and the overall experience was pleasant.',
      name: 'Daniel Brown',
      position: 'Fashion Blogger',
      image: '/images/avatars/avatar2.png',
    },
    {
      id: '6',
      rating: 4.7,
      text: 'Impressive collection of clothes! The shop offers a wide range of styles suitable for various occasions. Prices are reasonable for the quality you get.',
      name: 'Sophia Lee',
      position: 'Fashion Designer',
      image: '/images/avatars/avatar1.png',
    },
  ],
};
